theme: jekyll-theme-cayman

# Name of your site (displayed in the header)
title: <img src="https://huebner.github.io/snatchstart.jpg" width="100" height="100"> Marianne's Training Pages 

# Short bio or description (displayed in the header)  It was #name before.
description: I love weightlifting

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
#https://huebner.github.io/snatchstart.jpg
