theme: jekyll-theme-cayman

# Name of your site (displayed in the header)
name: Marianne's Training Pages

# Short bio or description (displayed in the header)
description: I love weightlifting

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
avatar: https://huebner.github.io/snatchstart.jpg
