theme: jekyll-theme-cayman

# Name of your site (displayed in the header) It was #name before.
title: <img src="https://huebner.github.io/snatchstart.jpg" width="100" height="100"> Marianne's Training Pages <img src="https://huebner.github.io/snatchfinish.jpg" width="100" height="200">

# Short bio or description (displayed in the header)  
description: 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
avatar: https://huebner.github.io/snatchstart.jpg
# doesn't seem to work
